// Playground paste-kind detection (HTML vs JSX). The JSX/HTML toggle was
// retired from the toolbar (2026-05-20) — gallery templates ship with their
// mode set per file — but the PLAYGROUND has no template, so a paste from
// ChatGPT / Claude / a local file can be either format. Without detection,
// pasting an HTML doc into the JSX-default playground throws
// `Unexpected token` on `<!DOCTYPE>` and the user sees a blank/error preview.
//
// Two layers, by cost + safety:
//   - detectKindByPrefix: cheap, runs on every keystroke. Flips only on
//     STRONG, unambiguous prefixes so half-typed JSX never swaps underneath
//     the user. Now also tolerates a leading markdown code fence and leading
//     HTML comments (common in real AI output).
//   - detectFragmentKind: a strict-JSX parse check for HTML fragments that
//     don't start with <!doctype/<html (e.g. `<section>…</section>`). Heavier,
//     so callers run it ONLY on a paste-sized delta — see Workspace.

import { parsesAsPlainJsx } from "./ast";

export type PasteKind = "html" | "jsx";

// Strip detection noise: leading whitespace, one leading markdown code fence
// the user forgot to remove (```html / ``` / ```jsx / ```tsx), and any leading
// HTML comments (a full doc can be prefixed by `<!-- generated by … -->`).
export function stripDetectionNoise(src: string): string {
  let s = src.replace(/^\s+/, "");
  s = s.replace(/^```[a-zA-Z]*[^\S\n]*\n?/, "");
  s = s.replace(/^\s+/, "");
  for (;;) {
    const m = s.match(/^<!--[\s\S]*?-->\s*/);
    if (!m) break;
    s = s.slice(m[0].length);
  }
  return s;
}

// Cheap prefix detection — safe to call on every keystroke.
export function detectKindByPrefix(src: string): PasteKind | null {
  const lower = stripDetectionNoise(src).toLowerCase();
  if (lower.startsWith("<!doctype html") || lower.startsWith("<html")) {
    return "html";
  }
  if (
    lower.startsWith("function ") ||
    lower.startsWith("const ") ||
    lower.startsWith("import ") ||
    lower.startsWith("export ") ||
    lower.startsWith('"use ') ||
    lower.startsWith("'use ")
  ) {
    return "jsx";
  }
  return null;
}

// Parse-based HTML-fragment detection. Only ever returns "html" (never flips
// the other way). Call ONLY on a paste-sized delta so it can't swap kind
// underneath half-typed JSX. An AI fragment like
// `<section class="hero"><img src="..."></section>` parses as HTML but FAILS a
// strict JSX parse (unclosed void tags, raw `<!--` children); `class=` alone is
// NOT used as a signal because it also parses in JSX.
export function detectFragmentKind(src: string): PasteKind | null {
  const cleaned = stripDetectionNoise(src);
  if (!cleaned.startsWith("<")) return null;
  // Strong JSX-only signals → it's JSX, never flip.
  if (/className\s*=|=>|\bimport\s|\bexport\s|\{\s*\/\*/.test(cleaned)) {
    return null;
  }
  // Strict JSX parse mirrors the preview's Babel-standalone (JSX, no TS). If
  // the markup fails it but looks like markup, it's HTML.
  if (!parsesAsPlainJsx(cleaned)) return "html";
  return null;
}
