#!/usr/bin/env node
// Screenshot the hero of every `web/*.html` template via headless Chromium
// and save them as `public/thumbs/<slug>.webp` so the gallery cards can show
// real previews instead of a text placeholder.
//
// Screenshots the HTML (not JSX) because the HTMLs are self-contained files
// a browser can load via `file://` without our preview-iframe runtime.
// Every web/<slug>.html has a matching web/<slug>.jsx generated by
// `scripts/html-to-jsx.mjs`, so the same thumb works for both formats.
//
// Run:  node scripts/gen-thumbs.mjs
//
// Tunables:
//   VIEWPORT_W / VIEWPORT_H — how wide/tall the hero capture is
//   CONCURRENCY             — pages in flight at once (beware flaky external
//                             fonts / image CDNs when cranked high)
//   PAGE_WAIT_MS            — extra settle time after networkidle before snap
//   TIMEOUT_MS              — hard ceiling per template

import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import puppeteer from "puppeteer";

const WEB_DIR = path.resolve(process.cwd(), "web");
const TEMPLATES_DIR = path.resolve(process.cwd(), "templates");
const OUT_DIR = path.resolve(process.cwd(), "public", "thumbs");
const VIEWPORT_W = 1280;
const VIEWPORT_H = 800;
const CONCURRENCY = 3;
const PAGE_WAIT_MS = 700;
const TIMEOUT_MS = 20000;
// Raise the CDP-level timeout so pages with heavy paint work (three.js,
// variable icon fonts, externally-hosted hero images) don't trip
// `Page.captureScreenshot`. Puppeteer's default is 30s; 120s leaves room for
// slow Google Fonts variable-font fetches + a handful of big image CDNs.
const PROTOCOL_TIMEOUT_MS = 120000;

function fileUrl(p) {
  // Cross-platform file:// URL. On Windows paths with spaces/backslashes, we
  // normalise forward slashes and URI-encode each segment.
  const normalised = p.replace(/\\/g, "/");
  const drive = /^[A-Za-z]:\//.test(normalised) ? "/" : "";
  return (
    "file://" +
    drive +
    normalised
      .split("/")
      .map((seg) => encodeURIComponent(seg).replace(/%3A/g, ":"))
      .join("/")
  );
}

function findExecutablePath() {
  // Use whichever Chrome/Chromium puppeteer or the OS provides.
  const candidates = [
    process.env.PUPPETEER_EXECUTABLE_PATH,
    process.env.CHROME_PATH,
    "/c/Program Files/Google/Chrome/Application/chrome.exe".replace(/\//g, path.sep),
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    "/usr/bin/chromium",
    "/usr/bin/google-chrome",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  ].filter(Boolean);
  return candidates;
}

async function screenshotOne(browser, target) {
  // `target` is { slug, srcPath } — srcPath points at the actual .html on
  // disk (web/<slug>.html OR templates/<slug>/source.html). Splitting the
  // resolution from the filename lets us thumbnail folder-templates
  // (coming-soon, hero-landing) the same way as web/ ones.
  const { slug, srcPath } = target;
  const out = path.join(OUT_DIR, `${slug}.webp`);
  // Skip if fresher than source (cheap incremental builds).
  try {
    const [src, dst] = await Promise.all([fs.stat(srcPath), fs.stat(out)]);
    if (dst.mtimeMs > src.mtimeMs) return { slug, skipped: true };
  } catch {
    // no dst yet, proceed
  }

  const page = await browser.newPage();
  try {
    await page.setViewport({ width: VIEWPORT_W, height: VIEWPORT_H, deviceScaleFactor: 1 });
    const url = fileUrl(srcPath);
    await page.goto(url, { waitUntil: "networkidle2", timeout: TIMEOUT_MS });
    // Small settle — lets Tailwind CDN do its first scan + fonts paint.
    await new Promise((r) => setTimeout(r, PAGE_WAIT_MS));
    await page.screenshot({
      path: out,
      type: "webp",
      quality: 78,
      clip: { x: 0, y: 0, width: VIEWPORT_W, height: VIEWPORT_H },
    });
    return { slug, ok: true };
  } catch (e) {
    return { slug, error: e instanceof Error ? e.message : String(e) };
  } finally {
    try {
      await page.close();
    } catch {}
  }
}

async function collectTargets() {
  const targets = [];
  // web/<slug>.html — bulk gallery templates.
  try {
    for (const name of await fs.readdir(WEB_DIR)) {
      if (!/\.html$/i.test(name)) continue;
      const slug = name.replace(/\.html$/i, "");
      targets.push({ slug, srcPath: path.join(WEB_DIR, name) });
    }
  } catch {}
  // templates/<slug>/source.html — folder-based seed templates (per spec
  // §10). Folder slugs may collide with web/ slugs in theory; the web/ entry
  // wins because it's added first, but in practice the seed slugs
  // (hero-landing, product-card, coming-soon) don't appear in web/.
  try {
    const haveWebSlugs = new Set(targets.map((t) => t.slug));
    for (const dir of await fs.readdir(TEMPLATES_DIR)) {
      const src = path.join(TEMPLATES_DIR, dir, "source.html");
      try {
        const stat = await fs.stat(src);
        if (!stat.isFile()) continue;
      } catch {
        continue;
      }
      if (haveWebSlugs.has(dir)) continue;
      targets.push({ slug: dir, srcPath: src });
    }
  } catch {}
  return targets;
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });
  const targets = await collectTargets();
  console.log(`Generating thumbnails for ${targets.length} HTML templates → ${OUT_DIR}`);

  // Try puppeteer's bundled chromium first; if none, try system Chrome.
  let browser;
  const execCandidates = findExecutablePath();
  let lastErr;
  for (const exe of [undefined, ...execCandidates]) {
    try {
      browser = await puppeteer.launch({
        headless: "new",
        executablePath: exe,
        protocolTimeout: PROTOCOL_TIMEOUT_MS,
      });
      if (exe) console.log(`using chrome at: ${exe}`);
      break;
    } catch (e) {
      lastErr = e;
    }
  }
  if (!browser) throw lastErr || new Error("no chromium available");

  let ok = 0;
  let skipped = 0;
  const failed = [];
  const queue = [...targets];
  const runOne = async () => {
    while (queue.length) {
      const t = queue.shift();
      if (!t) break;
      const r = await screenshotOne(browser, t);
      if (r.ok) {
        ok++;
        process.stdout.write(`✓ ${r.slug}${os.EOL}`);
      } else if (r.skipped) {
        skipped++;
      } else {
        failed.push(r);
        process.stdout.write(`✗ ${r.slug}: ${r.error}${os.EOL}`);
      }
    }
  };
  await Promise.all(Array.from({ length: CONCURRENCY }, runOne));

  await browser.close();
  console.log(`\nDone. ${ok} captured, ${skipped} up-to-date, ${failed.length} failed.`);
  if (failed.length) {
    for (const f of failed) console.log(`  - ${f.slug}: ${f.error}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
